on:
  # Trigger the workflow on push or pull request for the master branch
  push:
    branches:
      - master

name: Render Site

jobs:
  render:
    name: Render Site
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'gh-action-seb')"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and distill
        run: |
          install.packages("remotes")
          remotes::install_local(".")
          remotes::install_cran("rmarkdown")
          remotes::install_cran("distill")
        shell: Rscript {0}
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --all 'gh-action-seb re-build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
